<?php

/**
 * @file
 * Drupal hooks and global API functions to build nivo slider instance.
 *
 * This module provide ability for developer to easy construct and output the
 * new nivo slider instance.
 */
use Drupal\Core\Template\Attribute;

/**
 * Implements hook_menu().
 *
 * @todo remove in non-dev version
 */
function nivo_slider_api_menu() {
  $items = array();
  $items['nivo.slider.test'] = array(
    'title' => 'nivo slider api',
    'description' => 'nivo_slider_api_test',
    'menu_name' => 'Navigation',
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Example page how to use nivo_slider_api theme.
 *
 * @todo remove in non-dev version
 */
function nivo_slider_api_test() {
  // Load test data.
  $field_name = 'field_image';
  if (!field_info_field('node', $field_name)) {
    return t('There is no field with !name', array('!name' => $field_name));
  }

  $query = \Drupal::entityQuery('node');
    $query->condition('status', 1)
    ->condition($field_name, '', '!=');
  $result = $query
    ->range(0, 15)
    ->execute();

  $nodes = array();

  if (!empty($result)) {
    $nodes = node_load_multiple($result);
  }

  //return 'test';
  // Init vars.
  $captions = array();
  $slider_items = array();
  //dpm($nodes);
  //return 'asd';
  foreach ($nodes as $item) {
    $title = $item->getName();
    // Build images.
    $image = array(
      '#theme' => 'image_style',
      '#uri' => $item->field_image->entity->getFileUri(),
//      '#alt' => $title,
      // Associate slider item with caption item.
      '#title' => '#nid-' . $item->id(),
      '#style_name' => 'large',
    );
    // Wrapp images to links.
    $slider_items[] = array(
      '#type' => 'link',
      '#href' => 'node/' . $item->id(),
      '#title' => drupal_render($image),
      '#options' => array(
        // If link is image - this option always TRUE.
        'attributes' => array('title' => $title),
        'html' => TRUE,
      ),
    );
    // Caption item key will be a caption html element id attribute,
    // and value - content.
    // Example; $captions['fid-' . $item->fid] = $item->title.
    // Also, caption can be a render array.

    $captions['nid-' . $item->id()]['main_content']['#type'] = 'item_list';
    $captions['nid-' . $item->id()]['main_content']['#items'] = array($item->title);
    $captions['nid-' . $item->id()]['main_content']['#prefix'] = '<h3>';
    $captions['nid-' . $item->id()]['main_content']['#suffix'] = '</h3>';

    $captions['nid-' . $item->id()]['related_articles'] = array(
      '#theme' => 'item_list',
      '#items' => array(
        'Item 1',
        'Item 2',
      ),
    );
  }

  $options = array();
  // Add nivo slider settings.
  // You can customize all your slider inctances by passing a slider setting.
  $options['settings'] = array(
    'directionNav' => TRUE,
  );
  // Also, you can use your own theme,
  // (copy from nivo-slider some theme and paste it to you module).
  // You can chanege styles to your own needs.
  $theme_name = 'simplejstheme';
  $module_name = 'nivo_slider_api';
  $module_path = drupal_get_path('module', $module_name);
  $options['theme']['css'] = "$module_path/themes/$theme_name/$theme_name.css";
  $options['theme']['js'] = "$module_path/themes/$theme_name/$theme_name.js";
  // Name option is required.
  $options['theme']['name'] = $theme_name;

  return array(
    '#theme' => 'nivo_slider_api',
    '#items' => $slider_items,
    '#captions' => $captions,
    // Name of the slider. Must be unic.
    '#name' => 'test-slider',
    '#options' => $options,
    //'#attached' =>
  );
}

/**
 * Implements hook_theme().
 */
function nivo_slider_api_theme($existing, $type, $theme, $path) {
  return array(
    'nivo_slider_api' => array(
      'template' => 'nivo-slider',
      'render element' => 'elements',
    ),
  );
}

/**
 * Preprocess for nivo_slider_api_wrapper theme.
 */
function template_preprocess_nivo_slider_api(&$vars) {
  $options = $vars['elements']['#options'];

  if (!isset($vars['elements']['#name'])) {
    // Name option can`t be empty.
    return;
  }

  $name = $vars['elements']['#name'];
  $vars['name'] = $name;
  $vars['attributes'] = array('class' => '');
  $vars['attributes']['class'][] = 'nivo-slider-api-wrapper';
  $vars['attributes']['class'][] = 'nivo-slider-api-wrapper-' . $name;

  $default_settings = array();
  // Apply the slidr theme.
  if (isset($options['theme'])) {
    // Add wrappers classes.
    if (isset($options['theme']['name']) && !empty($options['theme']['name'])) {
      $vars['attributes']['class'][] = 'theme-' . $options['theme']['name'];
      $vars['attributes']['class'][] = 'slider-wrapper';
    }
    if (isset($options['theme']['css'])) {
      _drupal_add_css($options['theme']['css']);
    }
    if (isset($options['theme']['js'])) {
      // Make theme name visible in js files.
      $default_settings['theme_name'] = $options['theme']['name'];
      _drupal_add_js($options['theme']['js'], array('scope' => 'footer', 'weight' => 10));
    }
  }
  // Load default theme.
  else {
    _drupal_add_css('sites/all/libraries/nivo-slider/themes/default/default.css');
  }

  // Load library.
  _drupal_add_library('nivo_slider_api/jquery.nivo.slider');
  // Add default settings.
  $default_settings += array(
    'animSpeed' => 500,
    'captionOpacity' => 1,
    'controlNav' => TRUE,
    'controlNavThumbs' => FALSE,
    'directionNav' => TRUE,
    'directionNavHide' => TRUE,
    'effect' => "fade",
    'manualAdvance' => FALSE,
    'pauseOnHover' => FALSE,
    'pauseTime' => 5000,
    'slices' => 1,
    'startSlide' => 0,
    // Prev directionNav text.
    'prevText' => t('Prev'),
    // Next directionNav text.
    'nextText' => t('Next'),
  );
  // Add slider instance settings.
  $settings = $default_settings;
  if (isset($options['settings']) && !empty($options['settings'])) {
    $settings = array_merge($default_settings, $options['settings']);
  }
  $data = array('nivo_slider_api' => array($name => $settings));

  _drupal_add_js($data, 'setting');

  // Prepare slider items.
  $items = $vars['elements']['#items'];
  // Reset items variable.
  $vars['items'] = array();
  foreach ($items as $item) {
    if (is_array($item)) {
      // Expecst that the $item is a render array.
      $vars['items'][] = render($item);
    }
  }
  if (isset($vars['elements']['#captions']) && !empty($vars['elements']['#captions'])) {
    $captions = $vars['elements']['#captions'];
    // Reset captions variable.
    $vars['captions'] = array();
    foreach ($captions as $id => $caption) {
      // Expects that the $item is a render array.
      if (is_array($caption)) {
        $vars['captions'][$id] = render($caption);
      }
      elseif (is_string($caption)) {
        $vars['captions'][$id] = $caption;
      }
    }
  }

  // Run sliders.
  $vars['attributes'] = new Attribute($vars['attributes']);
  $vars['wrapper_attributes'] = $vars['attributes']->__toString();

  $module_path = drupal_get_path('module', 'nivo_slider_api');
  _drupal_add_js($module_path . '/nivo_slider_api.js', array('scope' => 'footer', 'weight' => 0));
}
